<link rel="stylesheet" href="/web/css/reset.css">
<link rel="stylesheet" href="/web/lib/bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="/web/lib/adminlte/css/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/web/lib/adminlte/css/ionicons.min.css">
<link rel="stylesheet" href="/web/lib/adminlte/css/AdminLTE.min.css">
<link rel="stylesheet" href="/web/lib/datetimepicker/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="/web/lib/datatable/datatables.bootstrap.css">
<link rel="stylesheet" href="/web/lib/adminlte/css/morris.css">
<link rel="stylesheet" href="/web/css/public.css">